# -*- coding: utf-8 -*-
"""chatbot_inspirate.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1935tvr6on5FgDCXRb9ZZxmhza_Pz8dR3
"""

# Importaciones necesarias para la aplicación Streamlit
import streamlit as st
from fuzzywuzzy import fuzz # Necesario para la coincidencia difusa (fuzzy matching)

# --- Configuración Inicial ---

# Título y encabezado de la aplicación
st.set_page_config(page_title="Inspírate Anímate Chatbot", layout="wide")
st.title("Inspírate Anímate")
st.markdown("¡Hola! Soy tu asistente virtual. Pregúntame sobre la personalización de nuestros cuadernos, llaveros y pines.")

# --- Base de Conocimiento (Knowledge Base) ---
# Definimos las preguntas clave y sus respuestas.
# La base de conocimiento se ha consolidado con todas las nuevas entradas.

KNOWLEDGE_BASE = {
    # CUADERNOS
    "cuadernos tamaño dimensiones": {
        "respuesta": "El tamaño de nuestros cuadernos es de 16 centímetros de ancho por 22 centímetros de alto.",
        "keywords": ["tamaño", "dimensión", "medida", "cuaderno", "libreta"]
    },
    "cuaderno hojas rayadas cuadriculadas puntos": {
        "respuesta": "Sí, las hojas son totalmente personalizables. Puedes elegir entre cuadriculadas, rayadas o con puntos.",
        "keywords": ["hojas", "cuadriculadas", "rayadas", "puntos", "personalizadas", "tipo"]
    },
    "cuaderno portada contraportada guardas hojas personalizacion": {
        "respuesta": "Sí, puedes personalizar todo del cuaderno: portada, contraportada, guardas y hojas.",
        "keywords": ["hojas", "portada", "contraportada", "guardas", "personalizadas"]
    },
    "cuaderno argollado cocido": {
        "respuesta": "Nuestros cuadernos son argollados.",
        "keywords": ["argollado", "cocido", "encuadernacion"]
    },
    "cuaderno cantidad hojas": {
        "respuesta": "Nuestros cuadernos son de 80 hojas.",
        "keywords": ["cantidad", "hojas", "cuantas"]
    },
    "cuaderno pasta portada contraportada material": {
        "respuesta": "Los cuadernos son de pasta semi-dura de 3 milímetros de grosor con laminación en acabado brillante.",
        "keywords": ["pasta", "portada", "contraportada", "material", "acabado", "brillante", "mate", "dura"]
    },
    "cuaderno color argolla": {
        "respuesta": "La argolla de los cuadernos es de color blanco.",
        "keywords": ["color", "argolla", "resorte"]
    },
    "cuaderno precio costo": {
        "respuesta": "El precio de cada cuaderno es de $37.000 más el envío.",
        "keywords": ["precio", "costo", "valor", "cuaderno"]
    },
    "cuaderno bolsillo separador": {
        "respuesta": "Los cuadernos no tienen ni bolsillos ni separadores.",
        "keywords": ["bolsillo", "separador", "accesorio"]
    },

    # LLAVEROS
    "llaveros tamaño dimensiones": {
        # Se ha mantenido la última versión que indica el rango de 3cm a 5cm
        "respuesta": "El tamaño estándar de los llaveros varía desde 3 centímetros hasta 5 centímetros de alto.",
        "keywords": ["tamaño", "dimensión", "medida", "llavero"]
    },
    "llavero precio costo": {
        "respuesta": "El precio de cada llavero es de $13.500 más el envío.",
        "keywords": ["precio", "costo", "valor", "llavero"]
    },
    "llavero material": {
        "respuesta": "El material de los llaveros es plástico con resina.",
        "keywords": ["material", "que", "hecho"]
    },
    "llavero resistencia agua": {
        "respuesta": "No mojar los llaveros.",
        "keywords": ["resistencia", "agua", "mojar", "lluvia"]
    },

    # PINES
    "pines tamaño dimensiones": {
        "respuesta": "Los pines están disponibles en tamaños que van desde 3 centímetros hasta 7 centímetros de alto.",
        "keywords": ["tamaño", "dimensión", "medida", "pin", "pines"]
    },
    "pin material": {
        "respuesta": "El material de los pines es plástico con resina.",
        "keywords": ["material", "que", "hecho", "pin"]
    },
    "pin resistencia agua": {
        "respuesta": "No mojar los pines.",
        "keywords": ["resistencia", "agua", "mojar", "lluvia", "pin"]
    },

    # INFORMACIÓN GENERAL
    "imagen foto formato calidad": {
        "respuesta": "Para personalizar tu producto, por favor envía tu imagen o foto en formato .JPG o .PNG en la mejor calidad posible, que no se vea pixelada.",
        "keywords": ["imagen", "foto", "formato", "jpg", "png", "pixelada", "calidad", "envio"]
    },
    "metodo pago nequi anticipo": {
        "respuesta": "Para iniciar el proceso de diseño, solicitamos un anticipo del 50% del valor total del pedido mediante transferencia a Nequi. Una vez que el diseño esté finalizado, le enviaremos fotografías para su aprobación. Al confirmar, transfiere el 50% restante para el envío inmediato.",
        "keywords": ["metodo", "pago", "nequi", "transferencia", "anticipo", "como"]
    },
    "contraentrega": {
        "respuesta": "No tenemos servicio contraentrega por el proceso de diseño y personalización.",
        "keywords": ["contraentrega", "pago"]
    },
    "servicio domicilio entrega bogota servientrega": {
        "respuesta": "Si la entrega es en Bogotá, se enviará con un domiciliario en moto y el comprador paga el costo al recibir. Si es afuera de Bogotá, se envía por Servientrega y el comprador deberá pagar el excedente del envío.",
        "keywords": ["domicilio", "entrega", "envio", "bogota", "servientrega", "moto"]
    }
}

# --- Lógica de Procesamiento del Chatbot ---

def get_best_match_answer(user_input):
    """
    Busca la mejor respuesta en la base de conocimiento utilizando la coincidencia difusa (fuzzy matching).
    """
    user_input_lower = user_input.lower()
    best_score = 0
    best_answer = None

    # Iterar sobre cada entrada en la base de conocimiento
    for key, data in KNOWLEDGE_BASE.items():
        # Combinar todas las palabras clave y la clave principal para una mejor coincidencia
        combined_keywords = key + " " + " ".join(data["keywords"])

        # Calcular la similitud de la cadena (Ratio Token Set)
        # Esto es robusto incluso si el orden de las palabras cambia
        score = fuzz.token_set_ratio(user_input_lower, combined_keywords.lower())

        if score > best_score:
            best_score = score
            best_answer = data["respuesta"]

    # Definir el umbral de confianza para dar una respuesta
    CONFIDENCE_THRESHOLD = 50 # Un valor de 50 es generalmente bueno para preguntas de FAQ

    if best_score >= CONFIDENCE_THRESHOLD and best_answer:
        return best_answer
    else:
        # Respuesta por defecto si no hay coincidencia
        return "Disculpa, no entendí tu pregunta. Por favor, intenta reformularla o pregunta por el producto (cuadernos, llaveros, pines) y su característica (tamaño, material, precio)."

# --- Interfaz de Usuario de Streamlit ---

# Inicializar historial de chat si no existe
if "messages" not in st.session_state:
    st.session_state.messages = []
    # Mensaje de bienvenida inicial
    st.session_state.messages.append({"role": "assistant", "content": "¡Bienvenido a Inspírate Anímate! ¿En qué puedo ayudarte hoy?"})

# Mostrar mensajes históricos en el chat
for message in st.session_state.messages:
    with st.chat_message(message["role"]):
        st.write(message["content"])

# Área de entrada para el usuario
if user_prompt := st.chat_input("Escribe tu pregunta aquí:"):
    # 1. Mostrar el mensaje del usuario
    with st.chat_message("user"):
        st.write(user_prompt)

    # Agregar el mensaje del usuario al historial
    st.session_state.messages.append({"role": "user", "content": user_prompt})

    # 2. Obtener la respuesta del asistente
    assistant_response = get_best_match_answer(user_prompt)

    # 3. Mostrar la respuesta del asistente
    with st.chat_message("assistant"):
        st.write(assistant_response)

    # Agregar la respuesta del asistente al historial
    st.session_state.messages.append({"role": "assistant", "content": assistant_response})

# NOTA IMPORTANTE: Para que este código funcione,
# la librería 'fuzzywuzzy' debe estar instalada.
# Asegúrate de incluirla en un archivo 'requirements.txt' en tu repositorio:
# streamlit
# python-Levenshtein
# fuzzywuzzy